/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * Brandico, (C) 2012 by Vitaly Puzrin
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  
///
import 'package:flutter/widgets.dart';

class SocialIcons {
  SocialIcons._();

  static const _kFontFam = 'SocialIcons';

  static const IconData reddit = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData youtube = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData github_circled = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData tumblr = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData gmail = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData facebook_rect = const IconData(0xf301, fontFamily: _kFontFam);
  static const IconData twitter = const IconData(0xf302, fontFamily: _kFontFam);
  static const IconData twitter_bird = const IconData(0xf303, fontFamily: _kFontFam);
  static const IconData github = const IconData(0xf308, fontFamily: _kFontFam);
  static const IconData skype = const IconData(0xf30b, fontFamily: _kFontFam);
  static const IconData tumblr_rect = const IconData(0xf310, fontFamily: _kFontFam);
  static const IconData linkedin_rect = const IconData(0xf31b, fontFamily: _kFontFam);
  static const IconData instagram_filled = const IconData(0xf31f, fontFamily: _kFontFam);
}
